### ISSUE TITLE
crash on world join, with atm8 and opticmanager

### ISSUE THREAD

**Issue by gentlewatcher** [CreativeMD/CreativeCore#178]
Trying to use modern online picture frame as well as opticmanager, but without those installed and trying to load 1.9.1-1.9.3 with the all the mods 8 mod pack it crashes on world join.
[crash-2023-05-11_17.24.52-client.txt](https://github.com/CreativeMD/CreativeCore/files/11457179/crash-2023-05-11_17.24.52-client.txt)

With only the latest opticmanager for 1.19.2 and 1.9.3 of Creativecore it crashes on world join still, 

Wut core on its own with the mod pack is fine.
And with Creativecore and modern online picture frame by anar4732 it is also fine.

**Comment by DadoIrie** [comment]
Can confirm that - tested with only creativecore & opticmanager. The issue here is if updating forge beyond 43.2.3 (last working version) as everything above crashes Minecraft when joining a world. 
Here's the log: https://mclo.gs/HAxHu5X

hope this helps fixing it

**Comment by CreativeMD** [comment]
I'm sorry, but I have dropped support for 1.19.2 quite some time ago. This issue has been fixed for newer versions. Furthermore for responding that late.

**Comment by DadoIrie** [comment]
<del>if that isn't something big which needs much time and efforts in order to get fixed would you fix it for 1.19.2 as most big mods are on that version - as my modpack is centered around create & farmers delight and both are on 1.19.2 would really appreciate if that issue here could get fixed for 1.19.2 - again ofc if it not that much of a hassle and work</del>

EDIT: nvm thanks for the reply

**Comment by CreativeMD** [comment]
The mod is open source. It is not that difficult to set things up to fix it. I'm willing to help out if someone will try it.
