### ISSUE TITLE
[CreativeCore] MC 1.20.1 Java Resolution exception

### ISSUE THREAD

**Issue by Zarandolph01** [CreativeMD/CreativeCore#187]
(Exception in thread "main" java.lang.module.ResolutionException: Modules reforged_fabric_api and creativecore export package net.fabricmc.api to module clumps)
[latest.log](https://github.com/CreativeMD/CreativeCore/files/12520697/latest.log)
[launcher_log.txt](https://github.com/CreativeMD/CreativeCore/files/12520701/launcher_log.txt)

**Comment by Zarandolph01** [comment]
No, I did not download a fabric mod. The Reforged Fabric API is for mod developers to port fabric mods to Forge.

**Comment by CreativeMD** [comment]
The log you posted here shows something else, but by your short description I think there is a duplicate class issue. I thought forge could handle that, but seems like it does not. You can easily fix it by opening the CreativeCore jar file and delete the folder net.fabricmc.api.

Sorry for not responding earlier. I don't see a way to fix it otherwise. I need the classes to make my mods work on both forge and fabric.
