### ISSUE TITLE
Not sure if this is on purpose or not.

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [CreativeMD/CreativeCore#195]
Hello! So I found out recently that after I installed creativecore the resource packs I just installed do not show in the available side. I checked the mcmeta files of both resource packs that didn't show and they were fine. When I removed creativecore the resource packs showed again. I wanted to know if this was on purpose or not so I came here as I didn't know how else to ask or report this.

**Comment by catsonv12** [comment]
Yea, same here. I literally had the same problem at the same time as you. What a coincidence. I wonder it must be a bug or intentional though I'm not sure why it would be intentional.

**Comment by CreativeMD** [comment]
Can you tell me what resourcepacks were you using? Would be good if I can try it out myself. Also sorry for responding that late.

**Comment by RubyTheQuester** [comment]
it seems any resource pack, literally any resource pack will not show up

**Comment by CreativeMD** [comment]
Using Fabric or Forge?

**Comment by RubyTheQuester** [comment]
quilt, so basically fabric

**Comment by RubyTheQuester** [comment]
after doing some testing, it seems it may be another mod doing it that needs creative core, as i have readded creative core but my resource packs has not been "despawned". a strange oddity

**Comment by CreativeMD** [comment]
@RubyTheQuester can you test fabric instead of Quilt? There are some issues with Quilt and it is not officially supported.

**Comment by RubyTheQuester** [comment]
happens in fabric too, and on version 2.11.10 of creativecore. but not version 2.11.2

**Comment by CreativeMD** [comment]
What version of fabric are you using? What resourcepacks are you trying out? Can you post the latest.log (after you opened the resourcepacks screen)? I need more information to help out. Tested it myself and everything works fine.

**Comment by RubyTheQuester** [comment]
0.15.0 and quilt 0.22.0, I do not think the version of fabric or quilt matters as it happen on both with version 2.11.10. I believe it's because of the minecraft version. This is something I should had mentioned earlier. as I play on 1.20.2 instead of 1.20.1. Still a strange bug but an important part I should had mentioned. I'll share the latest.log from when i open in 1.20.2 if you want

**Comment by CreativeMD** [comment]
If it is fabric or quilt does matter. I also know why is causing the issue. I added a new feature to AmbientSounds where sounds have random playback offsets. In order to make it work I need to figure out the size of the sound file. For that I have to implement some code (forge and fabric specific) to get the size of the file. This is not compatible with Quilt. Pretty sure that causes some error when loading the resourcepack. Again the log would be quite important. Also the version of Fabric matters. This is only implemented for minecraft version 1.20.1, that's why the issue does not occur on any other version.

**Comment by RubyTheQuester** [comment]
Why go back to 1.20.1 after making a version for 1.20.2? and which logs do you want? The one for when using on MC version 1.20.2? and Fabric or Quilt? as the bug happen with both and have the same effect, regardless of version of either.

**Comment by CreativeMD** [comment]
I do not support 1.20.2. All I did is port it once. The issue occurs in mc 1.20.1, right? Just open the game in 1.20.1 with fabric installed. Go to the resourcepack screen. Maybe make a screenshot of your resourcepack folder and the available packs ingame. And send the latest.log as well.

**Comment by RubyTheQuester** [comment]
It does not happen on 1.20.1 for me, which is what I said earlier and why I don't think the version of fabric or quilt matters, as it is the Minecraft version that this bug happens on. Using the latest version of both on 1.20.1 instead of 1.20.2, this does not happen. 

The 1.20.1 versions of CreativeCore loads in on 1.20.2 and does not crash, but causes the resource pack bug. It also disables any zipped resource pack but not any standard folder resource pack, if you wanna look into the logic behind that. 

Do you want the 1.20.2 log regardless or not, since 1.20.4 is out?

**Comment by CreativeMD** [comment]
That is weird. No idea how this could happen in 1.20.2 ... is it also there in 1.20.4? I will not support 1.20.2 anymore.

**Comment by PlayerXYT** [comment]
I have the same problem with fabric 1.20.2, only resource packs in zip files are problematic, resource packs embedded in mods or in a directory work fine.

A longer version of my setup:
fabric V0.14.24 for minecraft V1.20.2 with fabric API V0.90.4
Creative core installed from [modrinth](https://modrinth.com/mod/creativecore) V2.11.16 for 1.20.4 or 1.20.1 both cause problems

**Comment by RubyTheQuester** [comment]
Very cool Gmail, only sending me the replay email now.
It doesn't happen on MC version 1.20.4, just something you with 1.20.2, or least that what can be assumed. Maybe it's because of the different version number?

**Comment by CreativeMD** [comment]
I don't think it has anything to do with the version number. As long as things work in 1.20.1 and 1.20.4 I will close the issue. 1.20.2 is obsolete and will not be supported anymore. I pretty sure all of you can switch away from 1.20.2, so I hope it does not bother you. If it happens in the order version make sure to let me know.

Also thanks for taking the time to report this issue and providing helpful feedback!
