### ISSUE TITLE
[Bug] Creative Core prevents some players from joining the server

### ISSUE THREAD

**Issue by zndrmn** [CreativeMD/CreativeCore#262]
Even though Creative Core isn't required, some modded clients are prevented from joining saying they don't have Creative Core installed. Which is weird because I can join on the same server with just a vanilla client with zero issues. Seems quite random.

In the logs it complains about something related to the resource packs the client is using(?) I would give you a log file but for some reason all of my log files were cut so yeah.

![image](https://github.com/user-attachments/assets/8088b2cf-c905-47b5-a3f3-2529c65592ae)

**Comment by SrRapero720** [comment]
you say about logs... can please upload those?
serverlogs and clientlogs please

**Comment by zndrmn** [comment]
Sorry I'll try and get logs for the error when I'm able to get someone to help me test things again

**Comment by CreativeMD** [comment]
If CreativeCore is installed on server side, the client requires it as well. The other way around this is not necessary.

**Comment by FifthTundraG** [comment]
> If CreativeCore is installed on server side, the client requires it as well. The other way around this is not necessary.

Might I ask why this is the case? I know this issue is pretty old so pardon me if I'm being annoying, but it seems a bit silly for a library mod to be required for clients. I only use CreativeCore for AmbientSounds, and using Essential's world hosting everyone else also needs to have CreativeCore installed. I don't see any surface-level reason why a client-only mod (I can connect to vanilla servers, after all) should be required for all clients connecting to a server. I'm sure I'm just missing something here, but as an amateur dev an explanation would be greatly appreciated 😊

**Comment by Dainsleif233** [comment]
> If CreativeCore is installed on server side, the client requires it as well. The other way around this is not necessary.

Can it provide a configuration to disable the registration of status effects like Xaero's Map?

**Comment by CreativeMD** [comment]
@FifthTundraG If CreativeCore is not installed on server side it is not required. This topic is about CreativeCore being installed on server side, but people not having it installed.

**Comment by FifthTundraG** [comment]
> @FifthTundraG If CreativeCore is not installed on server side it is not required. This topic is about CreativeCore being installed on server side, but people not having it installed.

I apologize if I wasn't clear, that's exactly what I was referring to. I have CreativeCore installed on my client, so when I'm hosting a world through Essential, all my mods (that aren't marked as client-side only) will also be server-side mods. I'm wondering why CreativeCore, if installed on the server side, is required for clients.

**Comment by CreativeMD** [comment]
If you host a lan world from your singleplayer that is unfortunately what you have to deal with. Sorry, but there is no way around it.

**Comment by SrRapero720** [comment]
@FifthTundraG I want to clarify this because not even CreativeMD understand your question
CreativeCore is not a client-side only mod/library, its a both side mod, it registers packets on client-side and server-side, it runs an API and a config system in the background. The modloader cannot handle unregistered stuff (specially for synchronization), and if a both-sides mod registers stuff that the other side can't understand then you get a crash.

If a client-side mod requires a both-sides mod, you have to include that both-sides mod in both-sides and just use the client-side mod... _in the client-side_.

_Why creativecore its a both-sides mod_?
because it was an API for GUI, configuration and rendering, networking its something that runs on client-side and server-side, while rendering only runs on client-side (because you cannot render on a server... right?).

Yes, ambientsounds is a client-side mod, but that doesn't make creativecore a client-side mod, its still needed on both-sides, no matter what mod uses it.

**Comment by FifthTundraG** [comment]
> @FifthTundraG I want to clarify this because not even CreativeMD understand your question
> CreativeCore is not a client-side only mod/library, its a both side mod, it registers packets on client-side and server-side, it runs an API and a config system in the background. The modloader cannot handle unregistered stuff (specially for synchronization), and if a both-sides mod registers stuff that the other side can't understand then you get a crash.
> 
> If a client-side mod requires a both-sides mod, you have to include that both-sides mod in both-sides and just use the client-side mod... _in the client-side_.
> 
> _Why creativecore its a both-sides mod_?
> because it was an API for GUI, configuration and rendering, networking its something that runs on client-side and server-side, while rendering only runs on client-side (because you cannot render on a server... right?).
> 
> Yes, ambientsounds is a client-side mod, but that doesn't make creativecore a client-side mod, its still needed on both-sides, no matter what mod uses it.

Thank you so much for such a detailed response! Very much appreciated from my side :)
